name: 'Run data update'

on:
   schedule:
      # run once a day
      - cron: '0 0 * * *'

jobs:
   update-data:
      runs-on: ubuntu-latest

      permissions:
         pages: write
         id-token: write
      steps:
         - uses: actions/checkout@v4
           with:
              token: ${{ secrets.GH_TOKEN }}

         # Install dependencies
         - name: Set up Python 3.11
           uses: actions/setup-python@v5
           with:
              python-version: 3.11.4
              architecture: x64

         - name: Install dependencies
           run: |
              pip install -r requirements.txt --no-cache-dir

         # Build the book
         - name: Update data
           run: python3 run.py
           env:
              DB_HOST: ${{ secrets.DB_HOST }}
              DB_USERNAME: ${{ secrets.DB_USERNAME }}
              DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
              DB_NAME: ${{ secrets.DB_NAME }}

         - name: Commit updated snapshots
           uses: EndBug/add-and-commit@v9
           id: commit
           with:
              add: './'
              message: '[Automatic] Update snapshots'
              default_author: github_actions
              github_token: ${{ secrets.GH_TOKEN }}
